services:
  postgres:
    image: postgres:16-alpine
    container_name: reviewer-assignment-postgres
    environment:
        POSTGRES_USER: reviewer_user
        POSTGRES_PASSWORD: reviewer_password
        POSTGRES_DB: reviewer_db
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U reviewer_user -d reviewer_db" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - reviewer-network

  migrate:
    image: migrate/migrate:v4.17.0
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://reviewer_user:reviewer_password@postgres:5432/reviewer_db?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
          condition: service_healthy
    networks:
      - reviewer-network

volumes:
    postgres_data:

networks:
    reviewer-network:
        driver: bridge