services:
  postgres:
    image: postgres:16-alpine
    container_name: reviewer-assignment-postgres
    environment:
        POSTGRES_USER: reviewer_user
        POSTGRES_PASSWORD: reviewer_password
        POSTGRES_DB: reviewer_db
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U reviewer_user -d reviewer_db" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - reviewer-network

  migrate:
    image: migrate/migrate:v4.17.0
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://reviewer_user:reviewer_password@postgres:5432/reviewer_db?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
          condition: service_healthy
    networks:
      - reviewer-network

  api:
    build: .
    container_name: reviewer_assignment_api
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: reviewer_user
      DB_PASSWORD: reviewer_password
      DB_NAME: reviewer_db
      DB_SSL_MODE: disable
      LOG_LEVEL: info
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
       - reviewer-network
    restart: unless-stopped

volumes:
    postgres_data:

networks:
    reviewer-network:
        driver: bridge